yy-hw5-post/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :posts
 
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

yy-hw5-post/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

yy-hw5-post/app/models/post.rb
class Post < ActiveRecord::Base 
  validates_length_of :title, :maximum => 255
end

yy-hw5-post/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

yy-hw5-post/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:edit, :update, :show, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      # redirect_to posts_path
      redirect_to(posts_path, :notice => 'Post was successfully created.')
        # format.html  { redirect_to(@post, :notice => 'Post was successfully created.') }
        # format.json  { render :json => @post, :status => :created, :location => @post }
    else
      render :action => 'new'
    end
  end

  def edit
    @post = Post.find (params[:id])
  end

  def update
    @post = Post.find (params[:id])
    if @post.update_attributes (post_params)
      redirect_to posts_path
    else
      render :action => :edit
    end
  end

  def destroy
    @post = Post.find (params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def show
    @post = Post.find (params[:id])
  end
  
   
  private
    def set_post
      @post = Post.find_by_id(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content)
    end
 end 

yy-hw5-post/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

yy-hw5-post/app/helpers/application_helper.rb
module ApplicationHelper
end

yy-hw5-post/app/helpers/posts_helper.rb
module PostsHelper
end

yy-hw5-post/app/helpers/welcome_helper.rb
module WelcomeHelper
end

yy-hw5-post/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YyHw5</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

yy-hw5-post/app/views/posts/_form.html.erb
<%= form_for @post do |form| %>
  <%= form.text_field :title %>
  <%= "Title #{@post.errors[:title]}" if @post.errors[:title] %></br>
  <%= form.text_area :content %><%= "Content" %></br>
  <%= form.submit %>
<% end -%>

yy-hw5-post/app/views/posts/edit.html.erb
<%= render :partial => 'form' %>

yy-hw5-post/app/views/posts/index.html.erb
<h1>My Blog</h1>

<table border="1">
  <thead>
    <tr>
      <th>Title</th>
      <th>Options</th>
    </tr>
  </thead>

  <% @posts.each do |post| %>
    <tr>
      <td><%= link_to post.title, post %></td>
      <td>
        <%= link_to 'Edit', edit_post_path(post.id) %>
        <%= link_to 'Delete', post, :method => 'delete' %>
      </td>
    </tr>
  <% end -%>
</table>

<p><%= link_to 'New Post', new_post_path %></p>

yy-hw5-post/app/views/posts/new.html.erb
<%= render :partial => 'form' %>

yy-hw5-post/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<%= @post.content %>

<a href="/posts/<%= @post.id %>/edit">Edit</a>

yy-hw5-post/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>