yy-hw4-simpleforum/simpleforum/config/routes.rb
Rails.application.routes.draw do
  root "categories#index"
  devise_for :users

  resources :categories
  resources :topics, except: [:index] do
    resources :posts, except: [:index, :show]
  end
end

yy-hw4-simpleforum/simpleforum/app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user,
             counter_cache: true
  has_many :topics,
           dependent: :destroy
  has_many :posts, through: :topics


  def self.for_select
    Category.all.map do |category|
      [category.name, category.id]
    end
  end
end

yy-hw4-simpleforum/simpleforum/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic,
             counter_cache: true,
             touch: true
  belongs_to :user,
             counter_cache: true
  has_one :category, through: :topics
end

yy-hw4-simpleforum/simpleforum/app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :category,
             counter_cache: true,
             touch: true

  belongs_to :user,
             counter_cache: true

  has_many :posts,
           dependent: :destroy
end

yy-hw4-simpleforum/simpleforum/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :categories,
           dependent: :destroy
  has_many :topics,
           dependent: :destroy
  has_many :posts,
           dependent: :destroy
end

yy-hw4-simpleforum/simpleforum/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) do |user_params|
        user_params.permit(:email, :password, :password_confirmation, :nick)
      end
    end
end

yy-hw4-simpleforum/simpleforum/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :show, :destroy]

  def index
    @categories = Category.all
  end

  def show
    @topics = @category.topics
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.user = current_user

    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render 'categories/new', alert: 'Category was not created.'
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to categories_path, notice: 'Category was successfully updated.'
    else
      render :edit, alert: 'Category was not updated.'
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, notice: 'Category was successfully destroyed.'
  end

  private
    def set_category
      @category = Category.find_by_id(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :description, :priority)
    end
end

yy-hw4-simpleforum/simpleforum/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_topic
  before_action :set_post, only: [:edit, :update, :destroy]
  respond_to :js

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.topic = @topic

    unless @post.save
      render 'topics/show', alert: 'Post was not created.'
    end
  end

  def edit
  end

  def update
    unless @post.update(post_params)
      render :edit, alert: 'Post was not updated.'
    end
  end

  def destroy
    @post.destroy
  end

  private
    def set_topic
      @topic = Topic.find_by_id(params[:topic_id])
    end

    def set_post
      @post = Post.find_by_id(params[:id])
    end

    def post_params
      params.require(:post).permit(:content, :priority)
    end
end

yy-hw4-simpleforum/simpleforum/app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :destroy, :edit, :update]

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user = current_user
    @topic.views = 0

    if @topic.save
      @post = @topic.posts.new
      @post.content = topic_params[:content]
      @post.priority = 0
      @post.user = current_user
      @post.save
      redirect_to @topic, notice: 'Topic was successfully created.'
    else
      render :new, alert: 'Topic was not created.'
    end
  end

  def show
    @posts = @topic.posts
    @topic.views += 1
    @topic.save
  end

  def edit
  end

  def update
    if @topic.update(topic_params)
      redirect_to @topic, notice: 'Topic was successfully updated.'
    else
      render :edit, alert: 'Topic was not updated.'
    end
  end

  def destroy
    @topic.destroy
    redirect_to root_path, notice: 'Topic was successfully destroyed.'
  end

  private
    def set_topic
      @topic = Topic.find_by_id(params[:id])
    end

    def topic_params
      params.require(:topic).permit(:name, :content, :priority, :category_id)
    end
end

yy-hw4-simpleforum/simpleforum/app/helpers/application_helper.rb
module ApplicationHelper
end

yy-hw4-simpleforum/simpleforum/app/views/categories/_form.html.haml
= simple_form_for @category do |f|
  = f.input :name 

  = f.button :submit

yy-hw4-simpleforum/simpleforum/app/views/categories/edit.html.haml
%h1
  Edit category

= render 'form'

= link_to 'Back', :back

yy-hw4-simpleforum/simpleforum/app/views/categories/index.html.haml
%p
  Categories:
%hr

- @categories.each do |category|
  %p
    = link_to category.name , category
  %p
    = category.description
  %p
    posts:
    = category.topics_count
  - if user_signed_in?
    = link_to "edit category", edit_category_path(category)
    = link_to "delete category", category, method: :delete, data: { confirm: 'Are you sure?' }
  %hr


- if user_signed_in?
  %p
    = link_to "add new category", new_category_path

yy-hw4-simpleforum/simpleforum/app/views/categories/new.html.haml
%h1
  Create new category

= render 'form'

= link_to 'Back', :back

yy-hw4-simpleforum/simpleforum/app/views/categories/show.html.haml
%p
  = @category.name
%hr

- @topics.each do |topic|
  %p
    = topic.title
  %p
    = topic.description

  <br>
  %p
    created:
    = time_ago_in_words topic.created_at
    ago by
    = topic.user.nick
  %p
    views:
    = topic.views
  - if user_signed_in?
    = link_to "edit post", edit_topic_path(topic)
    = link_to "delete post", topic, method: :delete, data: { confirm: 'Are you sure?' }
  %hr

%p
  = link_to "add new post", new_topic_path
  = link_to 'Back', :back

yy-hw4-simpleforum/simpleforum/app/views/layouts/_footer.html.haml
%footer

yy-hw4-simpleforum/simpleforum/app/views/layouts/_header.html.haml
%header
  - if user_signed_in?
    %p
      Welcome
      = current_user.nick + "^-^ !   "+"!   "
      = link_to 'logout', destroy_user_session_path, method: :delete
  - else
    = link_to 'login', new_user_session_path

yy-hw4-simpleforum/simpleforum/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      SimpleForum
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body

    %p.notice
      = notice
    %p.alert
      = alert

    = render 'layouts/header'

    = yield

    = render 'layouts/footer'

yy-hw4-simpleforum/simpleforum/app/views/posts/_form.html.haml
= simple_form_for [@topic, @post], remote: true do |f|
  = f.input :content
  = f.input :priority

  = f.button :submit

yy-hw4-simpleforum/simpleforum/app/views/posts/_post.html.haml
.post{:id => "post#{post.id}"}
  %hr
  %p
    = time_ago_in_words post.created_at
    ago
  %p
    author:
    = post.user.nick
  %p
    = post.content

  - if user_signed_in?
    = link_to 'edit post', edit_topic_post_path(@topic, post), remote: true
    = link_to 'delete post', [@topic, post], remote: true, method: :delete, data: { confirm: 'Are you sure?' }
  %hr

yy-hw4-simpleforum/simpleforum/app/views/posts/create.js.erb
$('#posts').append("<%= j (render @post) %>");
$('#post-form').slideUp(350);

yy-hw4-simpleforum/simpleforum/app/views/posts/destroy.js.erb
$('#post' + <%= j (@post.id.to_s) %>).remove();

yy-hw4-simpleforum/simpleforum/app/views/posts/edit.js.erb
$('#post-form').html("<%= j (render 'posts/form') %>");
$('#post-form').slideDown(350);
$('body').scrollTo($('#post-form'), 10);

yy-hw4-simpleforum/simpleforum/app/views/posts/new.js.erb
$('#post-form').html("<%= j (render 'posts/form') %>");
$('#post-form').slideDown(350);

yy-hw4-simpleforum/simpleforum/app/views/posts/update.js.erb
$('#post' + <%= j (@post.id.to_s) %>).html("<%= j (render @post) %>");
$('#post-form').slideUp(350);

yy-hw4-simpleforum/simpleforum/app/views/topics/_form.html.haml
= simple_form_for @topic do |f|
  = f.input :title
  = f.input :description 
  = f.input :category_id, collection: Category.for_select

  = f.button :submit

yy-hw4-simpleforum/simpleforum/app/views/topics/edit.html.haml
%h1
  Edit post
  = @topic.title

= render 'form'

= link_to 'Back', :back

yy-hw4-simpleforum/simpleforum/app/views/topics/new.html.haml
= render 'form'

= link_to "back", :back

yy-hw4-simpleforum/simpleforum/app/views/topics/show.html.haml
%h1
  = @topic.title

%div#posts
  = render @posts

- if user_signed_in?
  = link_to 'New Post', new_topic_post_path(@topic), remote: true

%div{:id => "post-form", :style => "display:none;"}

= link_to "Back", :back