final-project/config/routes.rb
Rails.application.routes.draw do
  root to: "todos#index"
  
  resources :todos, only: [:index, :new, :create]
  
  resource :session, only: [:new, :create]
end

final-project/app/models/todo.rb
class Todo < ActiveRecord::Base
end

final-project/app/models/user.rb
class User
  def initialize(email)
    @email = email
  end
  
  def todos
    Todo.where(email: @email)
  end

  def signed_in?
    @email.present?
  end
end

final-project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def authenticate
    if !signed_in?
      redirect_to new_session_path
    end
  end

  def signed_in?
    current_user.signed_in?
  end

  def sign_in_as(email)
    session[:current_email] = email   
  end
  
  def current_user
    User.new(session[:current_email])
  end
end

final-project/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    sign_in_as params[:session][:email]
    redirect_to root_path
  end 
end

final-project/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate

  def index
    @todos = current_user.todos 
  end

  def new
    @todo = Todo.new
  end

  def create
    current_user.todos.create(todo_params)
    redirect_to root_path
  end

  private

  def todo_params
    params.require(:todo).permit(:title)
  end
end

final-project/app/helpers/application_helper.rb
module ApplicationHelper
end

final-project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <h1>Todos</h1>
<%= yield %>

</body>
</html>

final-project/app/views/todos/index.html.erb
<ul class="todos">
  <% @todos.each do |todo| %>
    <li><%= todo.title %></li>
  <% end %>
</ul>

<%= link_to "Add a new todo", new_todo_path %>

final-project/app/views/todos/new.html.erb
<%= form_for @todo do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.submit "Submit" %>
<% end %>